-- ======================================================
-- Supabase SQL Query to create 'login' table (For Figure 1)
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/dasrkwfegjqhkalawdfu/sql/new
-- ======================================================

CREATE TABLE IF NOT EXISTS public.login (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user', -- 'user' or 'admin'
  user_name TEXT,
  login_time TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & allow anonymous inserts for logging logins
ALTER TABLE public.login ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public login inserts" 
ON public.login 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow read login records" 
ON public.login 
FOR SELECT 
USING (true);
