-- ======================================================
-- Supabase SQL Query to update existing 'login' table
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/dasrkwfegjqhkalawdfu/sql/new
-- ======================================================

-- 1. Create table if it doesn't exist yet
CREATE TABLE IF NOT EXISTS public.login (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  password TEXT,
  password_hash TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  user_name TEXT,
  login_time TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Update existing table (Add password_hash column if missing)
ALTER TABLE public.login ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE public.login ALTER COLUMN password DROP NOT NULL;

-- 3. Enable Row Level Security (RLS) & Policies
ALTER TABLE public.login ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public login inserts') THEN
    CREATE POLICY "Allow public login inserts" ON public.login FOR INSERT WITH CHECK (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow read login records') THEN
    CREATE POLICY "Allow read login records" ON public.login FOR SELECT USING (true);
  END IF;
END $$;
